language: node_js
cache: npm
notifications:
  email: false
node_js:
  - '10'
script:
  - npm run build
after_success:
  - if [ "$TRAVIS_BRANCH" = "main" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run semantic-release; fi
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
